name: TomeOfTheBees
version: v1.0.1
api-version: 1.13
main: com.hadenwatne.tomeofthebees.TOTB
author: Cynicalvoe
commands:
  bees:
permissions:
  bees.use:
    default: op
  bees.jar:
    default: op
  bees.status:
    default: op